

<!-- Begin Privacy Policy -->
<h1>PRIVACY POLICY</h1>
<br />
<br />
  	<h2>A. Introduction</h2>
		<p>The goal of the POLITICAL EXCHANGE Website (&quot;the PX Website&quot;) is NOT to keep the personal beliefs, feelings, and ideas of Candidates (defined in the Terms of Use) private from their Constituents (defined in the Terms of Use). However, while the PX Website strives to bring Candidates and Constituents &quot;face to face&quot;, we know that the privacy of certain personal information is absolutely necessary. As such, we provide this privacy statement explaining our online information practices and about the way your information is collected and used at the PX Website, and among a POLITICAL EXCHANGE network of affiliated websites (the &quot;PX Network&quot;), which includes any sites or services owned, operated or offered by or on behalf of The Political Exchange Corporation or its subsidiaries (collectively &quot;Political Exchange&quot;). Political Exchange may share information among its subsidiaries or sites that it owns or controls, but is always protected under the terms of this Privacy Policy.</p>
		<p>The PX Website may contain links to third-party sites. Once you enter another Web site (whether through an advertisement, service, or content link), be aware that Political Exchange is not responsible for the privacy practices of these other sites. We encourage you to look for and review the privacy statements of each and every Web site that you visit through a link or advertisement in the PX Network. </p>
		<p>While you may use some of the functionality of the PX Website without registration, many of the specific tools and services on our website require registration. If you use the PX Website without registering, the only information we collect will be Non-Personal Information through the use of Cookies or Web Beacons. If you choose to register with the PX Website for certain Interactive Tools or other services, we require you to submit Personally Identifiable Information. You are responsible for ensuring the accuracy of the Personally Identifiable Information you submit to the PX Website. Inaccurate information will affect the information you receive when using our site and tools and our ability to contact you as described in this Privacy Policy. For example, your email address should be kept current because that it is how we communicate with you.</p>
		<p>Thank you for visiting POLITICALEXCHANGE.COM. </p>
	<h2>B. Privacy Accreditation</h2>
		<p>To give you confidence that we adhere to strict privacy standards and that we comply with our own privacy practices, we participate in the following external, independent program: </p>
		<p>TRUSTe – Political Exchange is a licensee of the TRUSTe Privacy Program. The PX Website has been awarded TRUSTe's Privacy Seal signifying that this privacy policy and practices have been reviewed by TRUSTe for compliance with TRUSTe's program requirements including transparency, accountability and choice regarding the collection and use of your personal information. The TRUSTe program does not cover information that may be collected through downloadable software. TRUSTe's mission, as an independent third party, is to accelerate online trust among consumers and organizations globally through its leading privacy trustmark and innovative trust solutions. If you have questions or complaints regarding our privacy policy or practices, please contact us at:</p>
		<p>The Political Exchange Corporation<br />
  			1920 High St.<br />
  			Columbia, SC 29203</p>
			<p>Or call: 803-206-3140 </p>
			<p>If you are not satisfied with our response you can contact TRUSTe directly. As required of TRUSTe licensees, we will inform you of the following in this Privacy <br />
				<ul>  
					<li>What Personally Identifiable Information of yours we collect; </li>
					<li>Who is collecting the Information; </li>
  					<li>How the Information is used; </li>
  					<li>With whom (if anyone) the Information may be shared; </li>
  					<li>What choices you have about collection, use and distribution of the Information;</li>
  					<li>What kind of security procedures are in place to protect the loss, misuse or alteration of Information under our control; and, </li>
  					<li>How you can correct any inaccuracies in the Information. </li>
				</ul>
 			<p>Click on the TRUSTe logo above to verify our compliance with the TRUSTe Privacy Program. The TRUSTe certification only applies to the PX Network Web sites.</p>

  	<h2>C. Children's Privacy </h2>
  		<p>We are committed to protecting the privacy of children. The PX Website is not directed to, intended or designed for persons under the age of 13. The PX Website does not collect Personally Identifiable Information from any person Political Exchange actually knows is a child under the age of 13.  By downloading, viewing, installing or otherwise using the PX Website, you represent that you are at least 13 years of age.</p>

	<h2>D. Personally Identifiable Information </h2>
 		<p> We collect Personally Identifiable Information, like your name, email address, date of birth, and zip code, you provide to us when you register as a member/Constituent of the PX Web site and/or when you update your member profile. We use the Personally Identifiable Information that you provide to respond to your questions, provide you the specific services you select, and to send you emails about Web site maintenance and updates, for example. <br />
  Political Exchange may distribute Constituent contact information to Candidates. However, during registration, Constituents will have an opportunity to decline to be contacted by Candidates as described elsewhere within this Privacy Policy. <br />
  At registration and at various times as you use the PX Website, you will be given the option of receiving recurring informational/promotional newsletters via email from Political Exchange and/or directly from third parties. When you sign up for our email newsletters or at any time, you can choose to Opt-In to receiving additional promotional emails from Political Exchange or our Sponsors. In order to subscribe to POLITICAL EXCHANGE newsletters via email, we need your contact information, for example name and email address. You can unsubscribe from the newsletters by simply: 1) following the directions included at the bottom of each email newsletter you receive from Political Exchange; or 2) editing your member information. An email will be sent to confirm the updates you make to your selection of newsletters<br />
  If you have difficulties with our unsubscribe or subscribe service, please use our Customer Support Form to write us and let us know about your problem. POLITICAL EXCHANGE Customer Service will unsubscribe you from that newsletter in two to three business days.<br />
  In some cases, when you click on a link or an advertisement on our site, in an e-mail or newsletter, your browser may be momentarily directed to the website of a third party which, acting on behalf of Political Exchange (see Disclosure to Third Party Contractor Web sites, below), notes or &quot;counts&quot; your response to the e-mail or newsletter before re-directing your browser to your selected destination; this re-direction process may not be apparent to you.<br />
  This Privacy Policy does not apply to content, business information, ideas, concepts or inventions that you send to Political Exchange by email. If you want to keep content or business information, ideas, concepts or inventions private or proprietary, do not send them in an email to Political Exchange. We try to answer every email within 48 business hours, but are not always able to do so. </p>
	<h2>E. Correcting or Removing Disclosed Personally Identifiable Information</h2>
  		<p>Political Exchange may store user submitted in an active database for a period of six (6) months. After six (6) months, user submitted data, including Personally Identifiable Information will be held in an active database or on an inactive back-up medium for a period of not less than five (5) years. </p>
		<p>If you have a complaint, problem or would like to correct or remove your Personally Identifiable Information from our system, please use our Customer Support Form (on the Contact Us page of the PX Web site). A Political Exchange representative will forward your complaint or request to the appropriate internal Political Exchange department for a response or resolution. We try to answer every email within 48 business hours, but may not always be able to do so.<br />
  			<br />
		<p>If you want to (1) delete your Personally Identifiable Information from our systems, or (2) update the Personally Identifiable Information that you have provided to us, please make this request clear on our Customer Support Form. </p>

	<h2>F. Non-Personal Information </h2>
  		<p>We may collect Non-Personal Information about your use of our Web site, special promotions and newsletters, including tracking such use through programs such as Google® Analytics. <br />
  		We collect Non-Personal Information about your use of our Web site and your use of the Web sites of selected sponsors and advertisers through the use of Cookies. Every computer that accesses the PX Web site is assigned a different Cookie by the PX Website. The information collected by Cookies (i) helps us dynamically generate advertising and content on Web pages or in newsletters, (ii) allows us to statistically monitor how many people are using our Web site and selected sponsors' and advertisers' sites, (iii) how many people open our emails, and (iv) for what purposes these actions are being taken. We may use Cookie information to deliver certain advertisements to your browser on our owned or operated Web sites based on areas of the PX Web site that you have visited during the same session or to determine the popularity of certain content or advertisements. Cookies are also used to facilitate navigation aids and session timers. <br />
  		Most browser software can be set to reject all Cookies. Most browsers offer instructions on how to reset the browser to reject Cookies in the &quot;Help&quot; section of the toolbar. If you reject our Cookies, certain of the functions and conveniences of our Web site may not work properly but you do not have to accept our Cookies in order to productively use our site. We do not link Non-Personal Information from Cookies to Personally Identifiable Information without your permission. <br />
  		We also may use Web Beacons to collect Non-Personal Information about your use of our Web site and the Web sites of selected sponsors and advertisers, and your use of special promotions or newsletters. The information collected by Web Beacons (i) allows us to statistically monitor how many people are using our website and selected sponsors' and advertisers' sites, (ii) how many people open our emails, and (iii) for what purposes these actions are being taken. Also we may use web beacons and Cookies to deliver advertisements on any of the Web sites owned or operated by Political Exchange based on areas of our Web sites that you have visited during the same session. We do not link Non-Personal Information from Web Beacons to Personally Identifiable Information without your permission. <br />
  		Third parties under contract with Political Exchange may use Cookies or Web Beacons to collect Non-Personal Information about your usage of Web sites in the PX Network. These third parties may use this information, on our behalf, to help Political Exchange deliver our advertising on other sites on the Internet based on your browsing activity on our sites. Political Exchange may further tailor the advertising on these third party sites based on other Non-Personal Information such as your geographic location (zip code), gender and/or age range to the extent known by these third parties. These third parties have agreed not to use Non-Personal Information they collect from our sites except to deliver advertisements on our behalf. If your browser is set to reject cookies, the Non-Personal Information will not be sent to these third parties and will not be used to deliver ads on third party sites. <br />
</p>

<p><strong>G. Community, Blogs and other Public Forums</strong><br />
</p>
<p>The PX Web site features several community areas and other public forums where users with similar interests can share information and support one another or where users can post questions for experts or Candidates to answer. We also offer online discussions moderated by experts in politically related fields and/or between Candidates. Our communities are generally open to the public and should not be considered private.</p>
<p><strong>Any information you shared in any online community area (including Personally Identifiable Information) like a chat room, forum, town hall meetings, live debates or online discussion is by design open to the public and is not private. You should think carefully before posting any Personally Identifiable Information in any public forum. What you post can be seen, disclosed to or collected by third parties and may be used by others in ways we cannot control or predict, including to contact you for unauthorized purposes. As with any public forum on any site, the information you post may also show up in third-party search engines like Google, Yahoo, MSN, Bing etc. <br />
</strong></p>
<p>We use third parties like Blogger from Google to manage the blog(s) which appear on our site (&quot;PX Blogs&quot;). When you choose to reply to a post or create your own post on a PX Blogs, you will be given the option to create an account for Google Blogger, Google will share the information you post as necessary for us and Blogger to provide continued service and to allow you to post your blogs on both the Google Blogger site and the PX Web site. Google will share ownership of your information as necessary to continue to implement the blogs on our site and as described in the Google Blogger privacy policy. Political Exchange will use your information as described in this privacy policy.</p>
<p><strong>H. Market Research</strong></p>
<p><br />
  From time to time Political Exchange, or operations contractors acting on our behalf, conducts online research surveys through email invitations, pop-up surveys and/or online focus groups. When participating in a survey, we may ask you to enter Personally Identifiable Information. Political Exchange may combine your Personally Identifiable Information you submit in a survey with information about you from other sources. The information from other sources may include financial or other identifiable information. This Personally Identifiable Information is used by Political Exchange for research purposes. Aggregate Information from the survey results may be reported to our clients, sponsor and/or advertisers. Personally Identifiable Information collected through market research will be used only by Political Exchange and our service providers and contractors and will not be given or sold to any other third party without your consent or as otherwise allowed by this Privacy Policy. For general market research surveys we will not knowingly accept survey responses from or conduct interviews with any person under the age of 13.</p>
<p>When our research surveys collect Personally Identifiable Information like name, email address or contain additional opt in permissions for follow up or re-contact, or if a survey offers to provide remuneration of any kind, we will not knowingly accept participants in these instances under the age of 18. Authorized Market Research surveys that appear on the PX Web site will always include a link to this Privacy Policy. Political Exchange is not responsible for unauthorized market research surveys that are conducted on third party sites. It is possible that when you click on certain banner advertisements on the PX Web site to visit an advertiser's site that you may receive invitations to participate in market research surveys from the advertiser or other third party site. These surveys are not subject to this Privacy Policy and are not related to Political Exchange's research efforts. You should always read the privacy policy and or terms and conditions of use on third party sites so you can understand how these third parties use your information and what rights you have regarding its use.</p>
<p>In addition to collecting survey responses from our members/Constituents, Cookies may be used to authenticate respondents or to help you pick up where you left off in a survey. If you have Cookies disabled you may not be able to participate in some studies. Cookies may be used to connect survey data with PX Web site usage characteristics. In connection with surveys on our behalf and on behalf of our advertisers we may use Cookies to determine whether you have seen certain content or advertising so that we may request your opinions.</p>
<p><strong>I.  Information Collected by Third Parties Not Acting on Political Exchange's Behalf</strong></p>
<p><br />
  Sponsors or advertisers on the PX Web site may use their own Cookies, Web Beacons or other online tracking technologies in the banner advertisements served on the PX Web site and in emails, special promotions or newsletters we send you. Some advertisers use companies other than Political Exchange to serve their ads and to monitor users' responses to ads, and these companies (&quot;Ad Servers&quot;) may also collect Non-Personal Information through the use of Cookies or Web Beacons on our Web site. In certain situations, information collection may be facilitated by momentarily directing your browser to the Web site of an Ad Server or other third party acting on behalf of the sponsor, partner, or advertiser before re-directing your browser to its selected destination (e.g., back to the PX Web site to show the ad, or to the advertiser's website); this re-direction process will not be apparent to you. <br />
  We do not control these third parties' use of cookies or Web Beacons, or how they manage the non-personal information they gather through them. However, we do require sponsors, advertisers and Ad Servers who collect cookie or web beacon information through our Web site to agree that they will not collect any Personally Identifiable Information from our site without your consent. They have promised us they will not link any non-personal cookie or web beacon information collected by them on our site to Personally Identifiable Information they or others collect in other ways or from other sites except as may be described in connection with a particular program. For example, in connection with &quot;Ad links&quot; furnished by Yahoo, non-personal information sent by your browser to Yahoo when you click on a sponsored link or submit a query may be used by Yahoo as described in its privacy policy. <br />
  You should review the privacy policy of other sites you visit or link to from our site to understand how these other sites use cookies and how they use the information they collect through the use of cookies or web beacons on their own sites. Certain Ad Servers allow you to prevent them from collecting data through the use of cookies. In order to do so, you must Opt-out of such data collection with each individual site. Currently, you can Opt-out of Cookies for several Ad Servers by visiting the Network Advertising Initiative gateway Opt-out site. This website will also allow you to review the Ad Server's privacy policies. You can find additional information and resources about how to opt out of advertising and related cookies by visiting the World Privacy Forum's Site.<br />
  Political Exchange does not knowingly engage in business with any company that uses Spyware or Malware. We do not provide users with downloadable software that collects or uses Personally Identifiable Information without full disclosure and Opt-in consent.<br />
  J. Disclosure of Your Information<br />
  Except as described in this Privacy Policy or as specifically agreed to by you, Political Exchange will not disclose any Personally Identifiable Information it gathers from you on our website. We may only release Personally Identifiable Information to third parties: (1) to comply with valid legal requirements such as a law, regulation, search warrant, subpoena or court order; or (2) in special cases, such as in response to a physical threat to you or others, to protect property or defend or assert legal rights. In the event that we are legally compelled to disclose your Personally Identifiable Information to a third party, we will attempt to notify you unless doing so would violate the law or court order. In addition, we may disclose Personal Information as described below. </p>
<p>Political Exchange operations and maintenance contractors sometimes have limited access to your Personally Identifiable Information in the course of providing products or services to Political Exchange. These contractors include vendors and suppliers that provide us with technology, services, and/or content for the operation and maintenance of our Web site. Unless you have Opted-out of receiving emails and newsletters from Political Exchange, these contractors also may have access to your email address to send newsletters or special promotions to you on our behalf or to send emails to you for purposes such as conducting market research on our behalf. Access to your Personally Identifiable Information by these contractors is limited to the information reasonably necessary for the contractor to perform its limited function for Political Exchange. We also contractually require that our operations and maintenance contractors 1) protect the privacy of your Personally Identifiable Information consistent with this Privacy Policy, and 2) not use or disclose your Personally Identifiable Information for any purpose other than providing us with products and services as required by law. </p>
<p>Certain content and services offered to you through our website may be served on Web sites hosted and operated by a company other than Political Exchange (&quot;Third Party Contractor Web sites&quot;). Political Exchange does not disclose your Personally Identifiable Information to these Third Party Contractor Web sites without your consent, but you should be aware that any information you disclose once you access these other Web sites is not subject to this Privacy Policy. Political Exchange does not endorse and is not responsible for the privacy practices of these Third Party Contractor Web sites. You should review the privacy policy posted on the other Web site to understand how that Third Party Contractor Website collects and uses your Personally Identifiable Information. Political Exchange makes an effort to make it obvious to you when you leave our website and enter a Third Party Contractor Web site, either by requiring you to click on a link or by notifying you on the site before you visit the third party site. </p>
<p>Political Exchange also provides links to sites provided by Third Party Contractor Websites that have business arrangements with Political Exchange to pay commissions based on sales of products or services generated through Political Exchange. </p>
<p>In addition to the Third Party Contractor Web sites that you may access as described above, for your convenience there may be links to Third Party Web sites operated by companies that are not affiliated with the PX Web site and that do not have contracts to provide content or services through the PX Web site. These links may be found in advertisements, referenced within content, or placed beside the names or logos of sponsors. Political Exchange does not disclose your Personal Identifiable Information to these Third Party Websites without obtaining your consent. Political Exchange does not endorse and is not responsible for the privacy practices of these sites. If you choose to link to one of these Third Party Web sites, you should review the privacy policy posted on this other website to understand how that Third Party Web site collects and uses your Personally Identifiable Information. <br />
  K. Disclosure of Aggregate Information<br />
  Political Exchange may provide Aggregate Information to third parties. For example, we might inform third parties regarding the number of users of our website and the activities they conduct while on our site. We might also inform a third party (that may or may not be an advertiser on our site) that &quot;30% of our users are Pro-Choice&quot; or that &quot;25% of our users have visited Pro-Choice blogs located on the PX Web site&quot;, as examples. Depending on the circumstances, we may or may not charge third parties for this Aggregate Information. We require parties with whom we share Aggregate Information to agree that they will not attempt to make this information personally identifiable, such as by combining it with other databases. <br />
  L. How Political Exchange Handles Privacy and Security Internally<br />
  Here are some of the security procedures that Political Exchange uses to protect your privacy: <br />
	<ul>
  		<li>requires both a personal username (log-in name) and a password in order for users to access their Personally Identifiable Information; </li>
  		<li>requires a public 'nickname' different from the username and password, used for any public forums or discussion groups; </li>
  		<li>uses firewalls to protect information held in our servers; </li>
  		<li>utilizes Secure Socket Layer (SSL) encryption in transmitting Personally Identifiable Information to our servers. In order to take advantage of encryption technology, you must have an Internet browser which supports 128-bit encryption; </li>
  		<li>closely monitors the limited number of Political Exchange employees who have potential access to your Personally Identifiable Information; </li>
  		<li>requires all Political Exchange employees to abide by our Privacy Policy and to be subject to disciplinary action if they violate it; and, </li>
  		<li>backs-up our systems to protect the integrity of your Personally Identifiable Information.</li>
	</ul>
	</p>
<p>Despite Political Exchange's efforts to protect your Personally Identifiable Information, there is always some risk that an unauthorized third party may find a way around our security systems or that transmissions of your information over the Internet may be intercepted. </p>
<p><strong>M. Changes to This Privacy Policy</strong><br />
Personally Identifiable Information - We will inform you if a material change is made to the Privacy Policy, which means a change that expands the permissible uses or disclosures of Personally Identifiable Information allowed by the prior version of the Privacy Policy. Your continued use of the PX Web site will indicate acceptance of the changes. You may of course choose to Opt-out of continuing to use the PX Web site. Please exit the site immediately if you do not agree to the terms of this Privacy Policy or any revised policy.</p>
<p>Non-Significant Changes – Political Exchange may make non-significant changes to the Privacy Policy that do not affect Personally Identifiable Information. For these instances, Political Exchange may not notify you of such non-significant changes.<br />
  <br />
  We reserve the right to modify this privacy statement at any time, so please review it frequently. If we make material changes to this policy, we will notify you here, by email, and by means of a notice on our home page.</p>
<p><strong>N. Definitions</strong><br />
  Aggregate Information or Data: As a website gathers individual pieces of Non-Personal Information (see definition below) from its users, it may combine similar data from many or all the users of the website into one big &quot;batch&quot;. For example, the site may add up the total number of people in Columbia, South Carolina, (but not their names) who are seeking information about the Republican presidential candidate and compare that to the number of people in Petaluma, California seeking the same information. <br />
  This sort of statistical information is called Aggregate Data because it reflects the habits and characteristics of a large group of anonymous people. Web sites may use aggregate data or share it with their business partners so that the information and services they provide best meet the needs of the users. Aggregate data also helps advertisers and sponsors on the Web know how effectively they are reaching and meeting the needs of their target audience. <br />
  Cookie: A small data file that is stored on the hard drive of the computer you use to view a Web site. Cookies are placed by that site or by a third party with a presence on the site, such as an advertiser using a Web Beacon (see definition below) and are accessible only by the party or site that placed the Cookie (i.e. a Cookie placed on your computer by the PX Web site isn't accessed by any other site you visit but a Cookie placed on your computer by an advertiser may be accessed by any site on which that same advertiser has a presence). Cookies can contain pieces of Personally Identifiable Information. The PX Web site encrypts any Personally Identifiable Information it stores in its Cookies. These Cookies often are used to make the site easier to use. For example, if you check a box to ask that we store your user name on your computer so that you don't have to enter it each time you visit the site, it's stored in a Cookie on your computer. <br />
  Non-personal Information: Information that is not traceable back to any individual and cannot be used to identify an individual. For example, click stream information is Non-Personal Information, as is information such as gender, age, city and state when not linked with other Personally Identifiable Information. <br />
  Opt-In: Means you are actively indicating your preference to participate in a program, email, feature, tool, or enhancement on a Web site. Typically, if you &quot;Opt-in&quot; you must provide certain information, usually Personally Identifiable Information, to the Web site or otherwise actively indicate your choice or preference to participate in the Web site program. For example, if you wish to receive Candidate X's newsletter by email from the PX Web site, you must enter your email address and choose the type of newsletter by checking a box next to a statement such as: &quot;Yes, I'd like to receive a free subscription to Candidate X's Newsletter through the PX Web site.&quot; <br />
  Opt-Out: Means that if you do not take some action you are indicating your preference to participate in a program, email, feature, tool or enhancement on a Web site. Typically, if you &quot;Opt-out&quot; you must uncheck a box next to a stated preference or otherwise take some indicate action to indicate your preference not to participate in a program. For example, if you do not wish to receive promotional emails from Political Exchange or its sponsors, you must uncheck the box in your email preference center that states, for example: &quot;Please send me special offers and communications from Political Exchange and/or its partners that would interest me.&quot; <br />
  Personally Identifiable Information: (also called Personal Information): Information that can be traced back to an individual (contrast with Non-Personal Information and Aggregate Information). Examples of Personally Identifiable Information include your name, home address, telephone number, email address, and Social Security number. <br />
  If other pieces of information are linked to Personally Identifiable Information, they also become Personally Identifiable Information. For example, if you use a nickname to chat online and give out your real name while chatting, your nickname becomes Personally Identifiable Information when linked with other Personally Identifiable Information. <br />
  SSL (Secure Sockets Layer): A security protocol developed by Netscape for transmitting private information via the Internet. SSL works by using a private key to encrypt data that's transferred over the SSL connection. Both Microsoft Internet Explorer (http://www.webopedia.com/TERM/S/Internet_Explorer.htm) and Netscape Navigator (http://www.webopedia.com/TERM/S/Navigator.htm) support SSL, and many Web sites use the protocol to obtain confidential user information, such as credit card numbers. By convention, URLs that utilize an SSL connection start with https: instead of http. <br />
Web Beacons: (also often referenced as &quot;clear GIFs&quot;, &quot;web bugs&quot;, &quot;1-by-1 GIFs&quot;, &quot;Single-Pixel GIFs&quot;, &quot;1 x 1 Pixels&quot;, or &quot;clear Pixels&quot;): Tiny graphic image files, imbedded in a web page in GIF, jpeg or HTML format, typically used to monitor activity on a web page and send back to its home server (which can belong to the host site, a network advertiser or some other third party) information from your browser, such as the IP address, the URL of the page on which the beacon is located, the type browser that is accessing the site and the ID number of any Cookies on your computer previously placed by that server. Web Beacons can also be used to place a Cookie on your computer. </p>
<p>Privacy Policy updated November 30, 2011<br />
  ©2011 THE POLITICAL EXCHANGE CORPORATION. All rights reserved.</p>
</body>

<!-- End Privacy Party-->