<h2><strong>Political Exchange Terms of Participation and Viewing</strong></h2>
<p>PLEASE READ CAREFULLY THE FOLLOWING TERMS OF PARTICIPATION AND VIEWING. THE FOLLOWING TERMS AND CONDITIONS FOR THE POLITICAL EXCHANGE WEBSITE IS A LEGAL CONTRACT BETWEEN YOU AND THE POLITICAL EXCHANGE CORPORATION (&quot;PX&quot;).  BY REGISTERING FOR, ACCESSING, BROWSING, DOWNLOADING FROM OR USING, IN ANY WAY, THIS WEBSITE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THE FOLLOWING TERMS OF PARTICIPATION AND VIEWING, INCLUDING ANY AND ALL APPLICABLE LAWS, RULES AND REGULATIONS AND FUTURE MODIFICATIONS OR AMENDMENTS (COLLECTIVELY THE &quot;TERMS&quot;).  IF AT ANY TIME YOU DO NOT AGREE TO, OR WITH, THESE TERMS, PLEASE IMMEDIATELY TERMINATE YOUR USE OF THIS WEBSITE. PX RESERVES ALL RIGHTS NOT EXPRESSLY GRANTED IN THIS TERMS OF USE. BY USING THIS WEBSITE YOU REPRESENT THAT YOU HAVE NOT BEEN PREVIOUSLY SUSPENDED OR PROHIBITED FROM USING THE POLITICAL EXCHANGE WEBSITE.</p>
<p><br>
  1)	Eligibility to Participate or View</p>
<p>Registering to become a member of PX or use PX in any way, is void where prohibited.  By using PX, you represent and warrant the following: (a) you are 18 years of age or older; (b) all registration information you submit is truthful and accurate; (c) you will maintain the accuracy of such information; (d) your use of PX does not violate any of these Terms. Your account may be terminated and Content deleted if we believe you are less than 18 years of age. Additionally, candidates who are not already elected public officials must prove to us they are actually running for office. For a more detailed description you may refer to our Candidate Eligibility (<a href="/candidate">link</a>) page. </p>
<p>2)	Use by Members</p>
<p>The PX Services (defined below) are for the personal use of Members and may only be used for direct commercial purposes if they are specifically endorsed or authorized by PX. PX reserves the right to remove commercial content in its sole discretion. Illegal and/or unauthorized use of the PX Services, including, without limitation, collecting usernames, user id numbers, and/or email addresses of Members by electronic or other means for the purpose of sending unsolicited email or unauthorized framing of or linking to the PX Services, or employing third party promotional sites or software to promote profiles for money, is prohibited. Commercial advertisements, affiliate links, and other forms of unauthorized data collection or solicitation may be removed from Member (defined below) profiles without notice or explanation and may result in termination of Membership privileges. PX reserves the right to take appropriate legal action, including, without limitation, referral to law enforcement, for any illegal or unauthorized use of the PX Services. </p>
<p>3)	Posted Content </p>
<p>Please choose carefully the text, files, images, photos, video, sounds, musical works, works of authorship, or any other information or materials (&quot;Content&quot;) that you post on, through or in connection with the PX Services and that you provide to other Members. Your PX profile may not include any form of Prohibited Content, as outlined in Section 4 below. Despite this prohibition, information, materials, products or services provided by other PX Members (for instance, in their profiles) may, in whole or in part, be unauthorized, impermissible or otherwise violate the Terms, and PX assumes no responsibility or liability for this material. If you become aware of misuse of the PX Services by any person or Linked Service, please click on the &quot;Contact PX&quot; link at the bottom of the PX Website pages. <br>
  PX may reject, refuse to post or delete any Content for any or no reason, including, but not limited to, Content that in the sole judgment of PX violates the Terms or which may be offensive, illegal or violate the rights of any person or entity, or harm or threaten the safety of any person or entity. PX assumes no responsibility for monitoring the PX Services for inappropriate Content or conduct. If at any time PX chooses, in its sole discretion, to monitor the PX Services, PX nonetheless assumes no responsibility for the Content, no obligation to modify or remove any inappropriate Content, and no responsibility for the conduct of the Member submitting any such Content. <br>
  You are solely responsible for the Content that you post on, through or in connection with any of the PX Services, and any material or information that you transmit to other Members and for your interactions with other Members.<br>
  PX reserves the right (but is not obligated) to do any or all of the following:<br>
  a) 	record the dialogue or postings of any Member;<br>
  b) 	investigate an allegation that a communication does not conform to the terms of this section and determine in its sole discretion to remove or request the removal of the communication(s);<br>
  c) 	remove communications which are abusive, illegal, or disruptive, or that otherwise fail to conform with these Terms;<br>
  d) 	terminate a Member's access to any or all areas and/or the PX Website upon any breach of these Terms;<br>
  e) 	monitor, edit, or disclose any communication on the PX Website; and,<br>
  f) 	edit or delete any communication(s) posted on the PX Website, regardless of whether such communication(s) violate these standards.<br>
  4)	Prohibited Content and/or Participation </p>
<p>The following are examples of the kind of Content that is illegal or prohibited to post on, through or in connection with the PX Services. PX reserves the right to investigate and take appropriate legal action against anyone who, in PX's sole discretion, violates this provision, including, without limitation, removing the offending Content from the PX Services, terminating the Membership of such violators and/or reporting such Content or activities to law enforcement authorities. Prohibited Content includes, but is not limited to, Content that, in the sole discretion of PX: <br>
  a)	is patently offensive or promotes or otherwise incites racism, bigotry, hatred or physical harm of any kind against any group or individual; <br>
  b)	harasses or advocates harassment of another person; <br>
  c)	exploits people in a sexual or violent manner; <br>
  d)	contains nudity, excessive violence, or offensive subject matter or contains a link to an adult website; <br>
  e)	solicits or is designed to solicit personal information from anyone under 18; <br>
  f)	publicly posts information that poses or creates a privacy or security risk to any person; <br>
  g)	constitutes or promotes information that you know is false or misleading or promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous; <br>
  h)	constitutes or promotes an illegal or unauthorized copy of another person's copyrighted work, such as providing pirated computer programs or links to them, providing information to circumvent manufacturer-installed copy-protect devices, or providing pirated music or links to pirated music files; <br>
  i)	involves the transmission of &quot;junk mail,&quot; &quot;chain letters,&quot; or unsolicited mass mailing, instant messaging, &quot;spimming,&quot; or &quot;spamming&quot;; <br>
  j)	contains restricted or password only access pages or hidden pages or images (those not linked to or from another accessible page); <br>
  k)	furthers or promotes any criminal activity or enterprise or provides instructional information about illegal activities including, but not limited to, making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses; <br>
  l)	solicits or is designed to solicit passwords or personal identifying information for commercial or unlawful purposes from other Members; <br>
  m)	involves commercial activities and/or sales without prior written consent from PX such as contests, sweepstakes, barter, advertising, or pyramid schemes; <br>
  n)	includes a photograph or video of another person that you have posted without that person's consent; <br>
  o)	for band, comedy, filmmaker and other profiles, uses sexually suggestive imagery or any unfair, misleading or deceptive Content intended to draw traffic to the profile; <br>
  p)	violates or attempts to violate the privacy rights, publicity rights, copyrights, trademark rights, contract rights or any other rights of any person;<br>
  q)	criminal or tortious activity, including, but not limited to, child pornography, fraud, trafficking in obscene material, drug dealing, gambling, harassment, defamation, stalking, spamming, spimming, sending of viruses or other harmful files, copyright infringement, patent infringement, or theft of trade secrets; <br>
  r)	advertising to, or solicitation of, any Member to buy or sell any products or services through the unauthorized or impermissible use of the PX Services. You may not transmit any chain letters or junk email to other Members. In order to protect our Members from such advertising or solicitation, PX reserves the right to restrict the number of emails which a Member may send to other Members in any 24-hour period to a number which PX deems appropriate in its sole discretion. If you breach the Terms and send or cause to send (directly or indirectly) unsolicited bulk messages other unauthorized commercial communications of any kind through the PX Services, you acknowledge that you will have caused substantial harm to PX, but that the amount of such harm would be extremely difficult to ascertain. As a reasonable estimation of such harm, you agree to pay PX $100 for each actual or intended recipient of such unsolicited message or other unauthorized commercial communication you send through the PX Services; <br>
  s)	circumventing or modifying, attempting to circumvent or modify, or encouraging or assisting any other person in circumventing or modifying any security technology or software that is part of the PX Services; <br>
  t)	activity that involves the use of viruses, bots, worms, or any other computer code, files or programs that interrupt, destroy or limit the functionality of any computer software or hardware, or otherwise permit the unauthorized use of or access to a computer or a computer network; <br>
  u)	modifying, copying, distributing, downloading, scraping or transmitting in any form or by any means, in whole or in part, any Content from the PX Services other than your Content which you legally post on, through or in connection with the PX Services; <br>
  v)	providing or using &quot;tracking&quot; or monitoring functionality in connection with the PX Services, including, without limitation, to identify other Members' views, actions or other activities on the PX Services; <br>
  w)	covering or obscuring the banner advertisements and/or safety features (e.g., report abuse button) on your personal profile page, or any PX page via HTML/CSS or any other means; <br>
  x)	any automated use of the system, such as, but not limited to, using scripts to add friends or send comments, messages, status or mood updates, blogs or bulletins; <br>
  y)	interfering with, disrupting, or creating an undue burden on the PX Services or the networks or services connected to the PX Services; <br>
  z)	impersonating or attempting to impersonate PX or a PX employee, administrator or moderator, another Member, or person or entity (including, without limitation, the use of email addresses associated with or of any of the foregoing); <br>
  aa)	using the account, username, or password of another Member at any time or disclosing your password to any third party or permitting any third party to access your account; <br>
  bb)	selling or otherwise transferring your profile, your email address or URL; <br>
  cc)	using or distributing any information obtained from the PX Services in order to harass, abuse, or harm another person or entity, or attempting to do the same; <br>
  dd)	displaying an unauthorized commercial advertisement on your profile, or accepting payment or anything of value from a third person in exchange for your performing any commercial activity through the unauthorized or impermissible use of the PX Services on behalf of that person, such as placing commercial content on your profile, links to e-commerce sites not authorized by PX, posting status or mood updates, blogs or bulletins with a commercial purpose, selecting a profile with a commercial purpose as one of your top friends, or sending messages with a commercial purpose; <br>
  ee)	relaying email from a third party's mail servers without the permission of that third party; <br>
  ff)	using invalid or forged headers to disguise the origin of any Content transmitted to or through PX's computer systems, or otherwise misrepresenting yourself or the source of any message or Content; <br>
  gg)	using any automated system, including, but not limited to, scripts or bots in order to harvest email addresses or other data from the PX Website for the purposes of sending unsolicited or unauthorized material; <br>
  hh)	engaging in, either directly or indirectly, or encouraging others to engage in, click-throughs generated through any manner that could be reasonably interpreted as coercive, incentivized, misleading, malicious, or otherwise fraudulent; or <br>
  ii)	using the PX Services in a manner inconsistent with any of these Terms. </p>
<p>5)	Ownership of Content</p>
<p>PX does not claim any ownership rights in Content that you submit, publish, or display on, through, or in connection with PX, apart from the license discussed herein. After taking any of the aforementioned actions regarding your Content, you still retain any and all rights to the Content you legally possessed before taking such action, subject to the limited license contained within the Terms. By taking any of the aforementioned actions, you hereby grant PX a limited license to use, modify, delete from, add to, publically perform, publically display, reproduce, make derivative works and distribute such Content solely on, through, or in connection PX including in any media or medium, or any form, format, or forum. This license grants PX the right to sell or otherwise distribute your Content outside PX Services. After you remove or delete your Content, PX will discontinue distribution of that Content as soon as may be practicable. When such Content is no longer in distribution by PX, the license ends. <br>
  The license you grant PX pursuant to this Section is non-exclusive, fully paid and royalty-free, sub-licensable, and worldwide. <br>
  You represent and warrant that (i) you own all Content you publish, display, or submit on or through PX, or otherwise have permission from the lawful owner of the Content to perform the aforementioned actions and grant the limited license described in this Section of the Terms, and (ii) the publishing of your Content does not violate the privacy rights, publicity rights, copyrights, contract rights, or any other rights of any person or legal entity. You agree to pay for all royalties, fees, and any other monies owed any person or legal entity by reason of the use of any Content published by you on or through PX. Never post a picture or video of or with someone else unless you have their explicit permission.  It is strictly prohibited to upload Content of any kind that contains expressions of hate, abuse, offensive images or conduct, obscenity, pornography, sexually explicit or any material that could give rise to any civil or criminal liability under applicable law or regulations or that otherwise may be in conflict with these Terms. <br>
  You will not use our copyrights, trademarks (including, but not limited to Political Exchange, the Political Exchange and PX Logos, PX, Hot Seat, and Bleachers), any confusingly similar marks, or other intellectual property without our written permission.<br>
  Aside from your Content, PX contains Content belonging to PX, Candidates (defined below), Constituents (defined below), and other third-party licensors. Except as provided within the Terms, you may not copy, modify, translate, publish, broadcast, transmit, distribute, perform, display, sell, or otherwise use ANY Content on or through PX.<br>
  PX reserves the right to limit the storage capacity of Content submitted on, through, or in connection with PX. </p>
<p>6)	Term and Termination</p>
<p>For Constituents: These Terms, and any posted revision to these Terms, shall remain in full force and effect while you use the PX Services or are a Member. You may terminate your Membership at any time, for any reason, by following the instructions on the Member's Account Settings page. PX may terminate your Membership at any time, for any or no reason, with or without prior notice or explanation, and without liability. Furthermore, PX reserves the right, in its sole discretion, to terminate your access to all or any part of the PX Services at any time, for any or no reason, with or without prior notice or explanation, and without liability. In addition, PX reserves the right, in its sole discretion, to reassign or rename your profile URL. PX expressly reserves the right to remove your profile and/or deny, restrict, suspend, or terminate your access to all or any part of the PX Services if PX determines, in its sole discretion, that you have violated this Agreement or pose a threat to PX, its employees, business partners, Members and/or the public. Even after Membership is terminated, this Agreement will remain in effect. </p>
<p>For Candidates: Your term is governed by your Candidate Contract with PX, and such contract is hereby incorporated in its entirety by reference. Should your Candidate Contract conflict with anything within the Terms, your Candidate Contract controls. </p>
<p>7)	Fees</p>
<p>For Constituents: You acknowledge that PX reserves the right to charge for any portion of the PX Services and to change its fees (if any) from time to time in its discretion. If PX terminates your Membership because you have breached the Terms, you shall not be entitled to the refund of any unused portion of fees or payments (if any). </p>
<p>For Candidates: Your fee is governed by your Candidate Contract with PX, and such contract is hereby incorporated in its entirety by reference. Should your Candidate Contract conflict with anything within the Terms, your Candidate Contract controls.</p>
<p>8)	Safety</p>
<p>We do our best to keep PX safe, but we cannot guarantee it. We need your help to do that, which includes the following commitments: <br>
  a)	you will not send or otherwise post unauthorized commercial communications (such as spam) on PX;<br>
  b)	you will not collect Members' content or information, or otherwise access PX, using automated means (such as harvesting bots, robots, spiders, or scrapers) without our permission;<br>
  c)	you will not engage in unlawful multi-level marketing, such as a pyramid scheme, on PX;<br>
  d)	you will not upload viruses or other malicious code;<br>
  e)	you will not solicit login information or access an account belonging to someone else;<br>
  f)	you will not bully, intimidate, or harass any Member;<br>
  g)	you will not post content that is hateful, threatening, or pornographic, incites violence, or contains nudity or graphic or gratuitous violence;<br>
  h)	you will not use PX to do anything unlawful, misleading, malicious, or discriminatory;<br>
  i)	you will not do anything that could disable, overburden, or impair the proper working of PX, such as a denial of service attack; and,<br>
  j)	you will not facilitate or encourage any violations of the Terms or any law.</p>
<p>9)	Special Provisions for Advertisers</p>
<p>Your Advertising Contract with PX is hereby incorporated into the Terms in their entirety by reference. Should your Advertising Contract conflict with the Terms in any way, your Advertising Contract controls.</p>
<p>10)	Protecting Copyrights and Other Intellectual Property</p>
<p>PX respects the intellectual property of others, and requires that our users do the same. You may not upload, embed, post, email, transmit or otherwise make available any material that infringes any copyright, patent, trademark, trade secret or other proprietary rights of any person or entity. It is PX's policy to terminate, in appropriate circumstances, the Membership of repeat infringers. <br>
  If you believe your work has been copied and posted on or through the PX Services in a way that constitutes copyright infringement, please send PX's Copyright Agent a notification of claimed infringement with all of the following information: <br>
  a)	identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works are covered by a single notification, a representative list of such works; <br>
  b) 	identification of the claimed infringing material and information reasonably sufficient to permit us to locate the material on the PX Services (providing the URL(s) of the claimed infringing material satisfies this requirement); <br>
  c) 	information reasonably sufficient to permit us to contact you, such as an address, telephone number, and, if available, an email address; <br>
  d) 	a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; <br>
  e) 	a statement by you, made under penalty of perjury, that the above information in your notification is accurate and that you are the copyright owner or are authorized to act on the copyright owner's behalf; and, <br>
  f) 	your physical or electronic signature. <br>
  PX's Copyright Agent for notification of claimed infringement can be reached as follows: Lir Derieg, The Political Exchange Corporation, 1920 High St., Columbia, SC 29203. PX's Copyright Agent for notification of claimed infringement can also be reached electronically at lirderieg@gmail.com. PX provides certain tools and technologies to help facilitate copyright owners' control over their copyrighted works. In order to inquire about the availability of these tools and technologies, please contact PX's Copyright Agent at the email address listed above. </p>
<p>11)	Member Disputes</p>
<p>You are solely responsible for your interactions with other PX Members or any other parties with whom you interact through the PX Services. PX reserves the right, but has no obligation, to become involved in any way with these disputes. <br>
  You will resolve any claim, cause of action or dispute (&quot;Claim&quot;) you have with us arising out of or relating to the Terms or PX exclusively in a state or federal court located in Richland County. The laws of the State of South Carolina will govern these Terms, as well as any claim that might arise between you and us, without regard to conflict of law provisions. You agree to submit to the personal jurisdiction of the courts located in Richland County, South Carolina for the purpose of litigating all such claims.<br>
  If anyone brings a Claim against us related to your actions, content or information on PX, you will indemnify and hold us harmless from and against all damages, losses, and expenses of any kind (including reasonable legal fees and costs) related to such Claim.</p>
<p>12)	Disclaimer</p>
<p>The use of the PX WEBSite and the Content is at your own risk.<br>
  WE TRY TO KEEP PX ONLINE, BUG-FREE, AND SAFE, BUT YOU EXPRESSLY AGREE THAT THE USE OF THE PX WEBSITE IS AT YOUR OWN RISK.  THE PX WEBSITE AND ANY DATA, INFORMATION, THIRD-PARTY SOFTWARE, CONTENT (INCLUDING COMMERCIAL CONTENT), MATERIAL, MATERIAL REFERENCE SITES, SERVICES, OR APPLICATIONS MADE AVAILABLE IN CONJUNCTION WITH OR THROUGH THE PX WEBSITE ARE PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot;, &quot;WITH ALL FAULTS&quot; BASIS.  WE DO NOT GUARANTEE THAT PX WILL BE SAFE OR SECURE. WE ARE NOT RESPONSIBLE FOR ANY DAMAGES CAUSED BY COMMUNICATIONS FAILURES THAT ARISE OUT OF A LOW QUALITY NETWORK CONNECTION OR OUTAGE. PX, ITS LICENSORS, ITS SUPPLIERS, AND OTHER THIRD-PARTIES, TO THE FULLEST EXTENT PERMITTED BY LAW, DISCLAIM ALL REPRESENTATIONS AND WARRANTIES, EITHER EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT OF THIRD PARTIES' RIGHTS, AND FITNESS FOR PARTICULAR PURPOSE, WHETHER ORAL OR WRITTEN. YOU EXPRESSLY ACKNOWLEDGE THAT AS USED IN THIS DISCLAIMERS AND LIABILITY SECTION, THE TERM PX INCLUDES THE POLITICAL EXCHANGE CORPORATION,  THE POLITCAL EXCHANGE CORPORATION'S OFFICERS, DIRECTORS, EMPLOYEES, SHAREHOLDERS, AGENTS, LICENSORS, THIRD-PARTY PARTNERS, SUPPLIERS AND SUBCONTRACTORS. <br>
  UNDER NO CIRCUMSTANCES, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, WILL THE POLITICAL EXCHANGE CORPORATION OR ITS OFFICERS, DIRECTORS, OWNERS, AFFILIATES, CONTRACTORS, EMPLOYEES, AGENTS, THIRD-PARTY PARTNERS, LICENSORS, OR SUPPLIERS BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, PUNITIVE, RELIANCE, OR EXEMPLARY DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES ARISING FROM ANY UNSUCCESSFUL COURT ACTION OR LEGAL DISPUTE, LOST BUSINESS, LOST REVENUES OR LOSS OF ANTICIPATED PROFITS OR ANY OTHER PECUNIARY OR NON-PECUNIARY LOSS OR DAMAGE OF ANY NATURE WHATSOEVER), PERSONAL INJURY/WRONGFUL DEATH ARISING OUT OF OR RELATING TO THESE TERMS OR THAT RESULT FROM YOUR USE OR YOUR INABILITY TO USE THE WEBSITE MATERIALS AND/OR CONTENT (INCLUDING USER CONTENT AND COMMERCIAL CONTENT) ON THE PX WEBSITE OR ANY REFERENCE SITES, OR ANY OTHER INTERACTIONS WITH PX, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR EVEN IF PX OR A PX AUTHORIZED REPRESENTATIVE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. <br>
  IF YOU ARE A CALIFORNIA RESIDENT, YOU WAIVE CALIFORNIA CIVIL CODE §1542, WHICH SAYS: &quot;A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR.&quot; <br>
  You understand and acknowledge that you may be exposed to Content that is inaccurate, offensive, indecent or objectionable and you agree to waive any legal or equitable rights or remedies you may have against PX, THE POLITICAL EXCHANGE CORPORATION and their officers, directors, subsidiaries, affiliated companies and employees with respect thereto.<br>
  These limitations of liability also apply with respect to damages incurred by you by reason of any products or services sold or provided on any reference or third-party websites or otherwise by third-parties other than PX and received through or advertised on the PX Website or received through any reference or third-party websites.<br>
  Certain jurisdictions do not allow limitations on implied warranties or the exclusion or limitation of certain damages.  If you reside in such a jurisdiction, some or all of the above disclaimers, exclusions, or limitations may not apply to you, and you may have additional rights.  The limitations or exclusions of warranties, remedies or liability contained in these Terms apply to you to the fullest extent such limitations or exclusions are permitted under the laws of the jurisdiction where you are located.  In the event the aforementioned limitations do not apply to you, the PX Website shall be liable only to the extent of actual damages incurred by you, not to exceed U.S. $100. PX and any third parties mentioned on the PX Website are not liable for any personal injury, including death, caused by your use or misuse of the PX Website, Content or Public Areas. Any claims arising in connection with your use of the Website, any Content, or other information must be brought within one (1) year of the date of the event giving rise to such action occurred. Remedies under these Terms are exclusive and are limited to those expressly provided for in these Terms.<br>
  You acknowledge and agree that THE POLITICAL EXCHANGE CORPORATION and the PX Website have offered their products and services and entered into these Terms in reliance upon the warranty disclaimers and the limitations of liability set forth herein, that the warranty disclaimers and the limitations of liability set forth herein reflect a reasonable and fair allocation of risk between you and PX and that the warranty disclaimers and the limitations of liability set forth herein form an essential basis of the bargain between you and PX. PX would not be able to provide the PX Website to you on an economically reasonable basis without these limitations.<br>
  13)	Indemnity</p>
<p>You agree to save, defend, indemnify, and hold PX, its officers, directors, employees, agents, partners, affiliated companies, subsidiaries, contractors, licensors, and suppliers, harmless from and against any claims, losses, damages, actions or demands, liabilities and settlements including, without limitation, reasonable legal and accounting fees and other expenses resulting from, or alleged to result from: (1) your violation of these Terms; and (2) your use or misuse of the PX Website; and (3) any Content that you post, upload, download or otherwise submit to the PX Website. PX reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify PX, and you agree to cooperate with PX's defense of these claims.  PX will use reasonable efforts to notify you of any such claim, action, or proceeding upon becoming aware.</p>
<p>14)	Mobile</p>
<p>We currently provide our mobile services for free, but please be aware that your carrier's normal rates and fees, such as text messaging fees, will still apply.<br>
  In the event you change or deactivate your mobile telephone number, you will update your account information on PX within 48 hours to ensure that your messages are not sent to the person who acquires your old number.<br>
  You provide all rights necessary to enable Members to sync (including through an Application) their contact lists with any basic information and contact information that is visible to them on PX, as well as your name and profile picture.</p>
<p>15)	Amendments</p>
<p>We reserve the right to change and modify these Terms and the PX services at any time and without prior notification. From time to time, we may allow member voting regarding certain prospective and retrospective changes. If you are eligible to participate in a future PX vote, we will notify you of your eligibility and provide you with instructions for voting via the email address you provide during registration. </p>
<p>16)	Miscellaneous Provisions<br>
  a)	These Terms and the PX Privacy Policy (also available on our website) make up the entire agreement between the parties regarding PX, including any candidate agreement and/or constituent agreement and/or advertising agreement, and supersedes any prior agreements regarding usage of the PX Website.<br>
  b)	If any portion of these Terms is found to be unenforceable, the remaining portion will remain in full force and effect.<br>
  c)	If we fail to enforce any of these Terms, it will not be considered a waiver.<br>
  d)	Any amendment to or waiver of these Terms must be made in writing and signed by us.<br>
  e)	You will not transfer any of your rights or obligations under these Terms to anyone else without our consent.<br>
  f)	All of our rights and obligations under these Terms are freely assignable by us in connection with a merger, acquisition, or sale of assets, or by operation of law or otherwise.<br>
  g)	Nothing in these Terms shall prevent us from complying with the law.<br>
  h)	These Terms do not confer any third party beneficiary rights.<br>
  i)	You will comply with all applicable laws when using or accessing PX.<br>
  j)	The heading references herein are for convenience purposes only, do not constitute a part of these Terms, and will not be deemed to limit or affect any of the provisions hereof.<br>
  k)	The Terms are written in English (US). To the extent any translated version of the Terms conflicts with or alters the English version, the English version controls.<br>
  l)	When using the PX Website, information will be transmitted over a medium that may be beyond the control and jurisdiction of PX and its suppliers, licensors or other third-parties. Accordingly, PX assumes no liability for or relating to the delay, failure, interruption, or corruption of any data or other information transmitted in connection with use of the PX Website.</p>
<p>17)	Definitions</p>
<p>a)	By &quot;PX Services&quot; we mean the features and services we make available, including through (i) our website at www.PoliticalExchange.us and any other PX branded or co-branded websites (including sub-domains, international versions, widgets, and mobile versions); (ii) our Platform; (iii) social plugins and other similar offerings; and, (iv) other media, software (such as a toolbar), devices, or networks now existing or later developed.<br>
  b)	By &quot;Platform&quot; we mean a set of APIs and services that enable others, including application developers and website operators, to retrieve data from PX or provide data to us.<br>
  c)	By &quot;Application&quot; we mean any application or website that uses or accesses Platform, as well as anything else that receives or has received data from us.  If you no longer access Platform but have not deleted all data from us, the term application will apply until you delete the data.<br>
  d)	By &quot;use,&quot; &quot;publish,&quot; &quot;display,&quot; &quot;submit,&quot; and/or &quot;display,&quot; we mean use, copy, publicly perform or display, distribute, modify, translate, and create derivative works of.<br>
  e)	By &quot;Participation&quot; we mean all access given to member constituents after validly registering an account with PX including, but not limited to, submitting questions to a member candidate page, submitting questions during a Hot Seat debate, viewing all information posted by member candidates, and using The Bleachers. Additionally included is all access given member candidates after valid registration, including but not limited to, posting Content (written and video) on your candidate page, access to interested constituent contact information, challenging another candidate to a Hot Seat debate, accepting a Hot Seat debate challenge, and participating in a Hot Seat debate. <br>
  f)	By &quot;viewing&quot; we mean the limited access given to guest candidates and guest constituents which may include, but not necessarily limited to, limited viewing of some candidate pages and limited viewing of some Hot Seat debates. <br>
  g)	By &quot;Candidate&quot; we mean a person who meets all the qualifications explained on our Candidate Eligibility (Link) page.<br>
  h)	By &quot;Constituent&quot; we mean all persons who are 18 years of age or older, and who do not meet the qualifications to register as a candidate with PX.<br>
  i)	By &quot;Member&quot; we mean a candidate or constituent who has registered with PX, been granted a PX account, and may participate on PX. <br>
  j)	By &quot;Membership&quot; we mean the rights and responsibilities associated with being a Member, which are enumerated throughout these Terms.<br>
  k)	By &quot;Guest&quot; we mean a candidate or constituent who has not registered with PX and who only has limited viewing privileges. <br>
  l)	By &quot;non-exclusive&quot; we mean you are free to license your Content to anyone else in addition to PX.<br>
  m)	By &quot;fully-paid and royalty-free&quot; we mean that we are not required to pay you or anyone else deriving rights from you for the use on PX of any Content you may post.<br>
  n)	By &quot;sublicensable&quot; we mean that PX is free to use its affiliates, subcontractors, and other partners to provide PX services. <br>
  o)	By &quot;worldwide&quot; we mean the Internet and PX services are global in reach. <br>
</p>
<p>Date of Last Revision: November 30, 2011</p>
<p>©2011, The Political Exchange Corporation </p>
